//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Hivemapper : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Fly
        {
            get
            {
                return SteamVR_Actions.hivemapper_Fly;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.hivemapper_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.hivemapper_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.hivemapper_Menu;
            }
        }
    }
}
